/**
 * 与 service/src 各 *Controller 中 @Controller 注册的命令对齐（用于内部映射与文档）。
 * 新增后端命令时请同步更新此列表。
 */
export const SERVICE_COMMANDS: { command: string; hint: string }[] = [
  { command: 'connect', hint: '建立 MCP 连接，body 为 McpOptions' },
  { command: 'connect/list', hint: '列出当前 Gateway 内存中的 MCP 连接会话' },
  { command: 'lookup-env-var', hint: 'body: { keys: string[] }' },
  { command: 'ping', hint: 'body: { clientId }' },
  { command: 'disconnect', hint: 'body: { clientId }' },
  { command: 'server/version', hint: 'body: { clientId }' },
  { command: 'prompts/list', hint: 'body: { clientId }' },
  { command: 'prompts/get', hint: 'body: { clientId, promptId, args? }' },
  { command: 'resources/list', hint: 'body: { clientId }' },
  { command: 'resources/templates/list', hint: 'body: { clientId }' },
  { command: 'resources/read', hint: 'body: { clientId, resourceUri }' },
  { command: 'tools/list', hint: 'body: { clientId }' },
  { command: 'tools/call', hint: 'body: { clientId, toolName, toolArgs, callToolOption? }' },
  { command: 'llm/chat/completions', hint: '流式聊天（Web UI）；CLI 请用 llm/chat/completions/sync' },
  { command: 'llm/models', hint: 'body: { baseURL, apiKey, proxyServer? }' },
  { command: 'llm/models/openrouter', hint: '无额外字段' },
  { command: 'llm/chat/completions/sync', hint: 'body: { baseURL, apiKey, model, messages, temperature? }' },
  { command: 'llm/models/dynamic', hint: 'body: { providerId }' },
  { command: 'batch-validation/run', hint: 'body: { messages, testCases, llmConfig, evaluationMode?, customPrompt? }' },
  { command: 'connections/list', hint: 'body: { scope?, workspacePath? }；列出本地连接资源' },
  { command: 'connections/get', hint: 'body: { id, scope?, workspacePath? }；读取单个本地连接资源' },
  { command: 'connections/save', hint: 'body: { item, id?, name?, scope?, workspacePath? }；保存本地连接资源' },
  { command: 'connections/delete', hint: 'body: { id, scope?, workspacePath? }；删除本地连接资源' },
  { command: 'connections/connect', hint: 'body: { id, scope?, workspacePath? }；通过已保存连接建立会话' },
  { command: 'test-cases/load', hint: 'body: { clientId }；加载当前服务下保存的工具测试用例' },
  { command: 'test-cases/save', hint: 'body: { clientId, testCases }；保存工具测试用例与结果' },
  { command: 'test-cases/list', hint: 'body: { connectionId|clientId, scope?, workspacePath? }；列出本地工具测试用例' },
  { command: 'test-cases/get', hint: 'body: { connectionId|clientId, caseId, scope?, workspacePath? }' },
  { command: 'test-cases/upsert', hint: 'body: { connectionId|clientId, testCase, scope?, workspacePath? }' },
  { command: 'test-cases/delete', hint: 'body: { connectionId|clientId, caseId, scope?, workspacePath? }' },
  { command: 'validation-suites/list', hint: 'body: { connectionId|clientId, scope?, workspacePath? }；列出本地 validation suites' },
  { command: 'validation-suites/get', hint: 'body: { connectionId|clientId, suiteId, scope?, workspacePath? }' },
  { command: 'validation-suites/upsert', hint: 'body: { connectionId|clientId, suite, scope?, workspacePath? }' },
  { command: 'validation-suites/delete', hint: 'body: { connectionId|clientId, suiteId, scope?, workspacePath? }' },
  { command: 'setting/save', hint: 'body: 任意设置对象' },
  { command: 'setting/load', hint: '加载设置' },
  { command: 'skills/list', hint: '列出技能' },
  { command: 'skills/load', hint: 'body: { skillName }' },
  { command: 'skills/read-file', hint: 'body: { skill_name, file_path }' },
  { command: 'auth/login', hint: 'body: { username, password }' },
  { command: 'auth/register', hint: 'body: { email, username, password }' },
  { command: 'auth/oauth', hint: 'body: { channel, redirectUri? }' },
  { command: 'auth/oauth/finalize', hint: 'body: { nonce }' },
  { command: 'auth/device/start', hint: 'body: { channel }' },
  { command: 'auth/device/token', hint: 'body: { deviceCode }' },
  { command: 'auth/logout', hint: '' },
  { command: 'auth/logout-all', hint: '' },
  { command: 'auth/status', hint: '' },
  { command: 'auth/refresh', hint: '' },
  { command: 'auth/set-token', hint: 'body: { token }' },
  { command: 'auth/set-token-pair', hint: 'body: { accessToken, refreshToken, user? }' },
  { command: 'auth/get-token', hint: '' },
  { command: 'auth/clear-token', hint: '' },
  { command: 'projects/create', hint: 'body: { name, transport?, endpoint?, description?, enabled? }' },
  { command: 'projects/list', hint: '' },
  { command: 'projects/get', hint: 'body: { projectId }' },
  { command: 'projects/update', hint: 'body: { projectId, name?, transport?, endpoint?, description?, enabled? }' },
  { command: 'projects/delete', hint: 'body: { projectId }' },
  { command: 'projects/members/list', hint: 'body: { projectId }' },
  { command: 'projects/members/add', hint: 'body: { projectId, userId, role }' },
  { command: 'projects/members/remove', hint: 'body: { projectId, userId }' },
  { command: 'projects/members/update-role', hint: 'body: { projectId, userId, role }' },
  { command: 'projects/invites/list', hint: 'body: { projectId }' },
  { command: 'projects/invites/create', hint: 'body: { projectId, role, expiresAt?, maxUses? }' },
  { command: 'projects/invites/delete', hint: 'body: { projectId, inviteId }' },
  { command: 'projects/invites/revoke', hint: 'body: { projectId, inviteId }' },
  { command: 'invites/join', hint: 'body: { code, userId }' },
  { command: 'spec-cases/create', hint: 'body: { projectId, nodeType, type, toolName?, name, parentId?, input?, output?, description? }' },
  { command: 'spec-cases/tree', hint: 'body: { projectId }' },
  { command: 'spec-cases/get', hint: 'body: { projectId, caseId }' },
  { command: 'spec-cases/update', hint: 'body: { projectId, caseId, nodeType, type, toolName?, name, parentId?, input?, output?, description? }' },
  { command: 'spec-cases/delete', hint: 'body: { projectId, caseId }' },
  { command: 'batch-validation-cases/create', hint: 'body: { projectId, name, description?, testCasesJSON?, presetsJSON?, resultGroupsJSON? }' },
  { command: 'batch-validation-cases/list', hint: 'body: { projectId }' },
  { command: 'batch-validation-cases/get', hint: 'body: { projectId, caseId }' },
  { command: 'batch-validation-cases/update', hint: 'body: { projectId, caseId, name, description?, testCasesJSON?, presetsJSON?, resultGroupsJSON? }' },
  { command: 'batch-validation-cases/delete', hint: 'body: { projectId, caseId }' }
];
