export const SERVICE_COMMANDS: { command: string; hint: string }[] = [
  { command: 'connect', hint: 'body: McpOptions' },
  { command: 'connect/list', hint: 'List active Gateway MCP sessions' },
  { command: 'lookup-env-var', hint: 'body: { keys: string[] }' },
  { command: 'ping', hint: 'body: { clientId }' },
  { command: 'disconnect', hint: 'body: { clientId }' },
  { command: 'server/version', hint: 'body: { clientId }' },
  { command: 'prompts/list', hint: 'body: { clientId }' },
  { command: 'prompts/get', hint: 'body: { clientId, promptId, args? }' },
  { command: 'resources/list', hint: 'body: { clientId }' },
  { command: 'resources/templates/list', hint: 'body: { clientId }' },
  { command: 'resources/read', hint: 'body: { clientId, resourceUri }' },
  { command: 'tools/list', hint: 'body: { clientId }' },
  { command: 'tools/call', hint: 'body: { clientId, toolName, toolArgs, callToolOption? }' },
  { command: 'llm/chat/completions', hint: 'Streaming chat for Web UI' },
  { command: 'llm/models', hint: 'body: { baseURL, apiKey, proxyServer? }' },
  { command: 'llm/models/openrouter', hint: 'No extra fields' },
  { command: 'llm/chat/completions/sync', hint: 'body: { baseURL, apiKey, model, messages, temperature? }' },
  { command: 'llm/models/dynamic', hint: 'body: { providerId }' },
  { command: 'batch-validation/run', hint: 'body: { messages, testCases, llmConfig, evaluationMode?, customPrompt? }' },
  { command: 'debug-chat/run-agent', hint: 'body: { clientId, input, llmConfig }' },
  { command: 'servers/list', hint: 'List local MCP Servers' },
  { command: 'servers/get', hint: 'body: { id }' },
  { command: 'servers/save', hint: 'body: { scope?: local|auto, id?, ... }' },
  { command: 'servers/delete', hint: 'body: { id }' },
  { command: 'servers/replace-all', hint: 'body: { items }' },
  { command: 'test-cases/load', hint: 'body: { clientId }' },
  { command: 'test-cases/save', hint: 'body: { clientId, testCases }' },
  { command: 'test-cases/list', hint: 'body: { connectionId|clientId, scope?, workspacePath? }' },
  { command: 'test-cases/get', hint: 'body: { connectionId|clientId, caseId, scope?, workspacePath? }' },
  { command: 'test-cases/upsert', hint: 'body: { connectionId|clientId, testCase, scope?, workspacePath? }' },
  { command: 'test-cases/delete', hint: 'body: { connectionId|clientId, caseId, scope?, workspacePath? }' },
  { command: 'validation-suites/list', hint: 'body: { connectionId|clientId, scope?, workspacePath? }' },
  { command: 'validation-suites/get', hint: 'body: { connectionId|clientId, suiteId, scope?, workspacePath? }' },
  { command: 'validation-suites/upsert', hint: 'body: { connectionId|clientId, suite, scope?, workspacePath? }' },
  { command: 'validation-suites/delete', hint: 'body: { connectionId|clientId, suiteId, scope?, workspacePath? }' },
  { command: 'setting/save', hint: 'body: any settings object' },
  { command: 'setting/load', hint: 'Load settings' },
  { command: 'skills/list', hint: 'List skills' },
  { command: 'skills/load', hint: 'body: { skillName }' },
  { command: 'skills/read-file', hint: 'body: { skill_name, file_path }' }
];
