/**
 * 与 service/src 各 *Controller 中 @Controller 注册的命令对齐（用于内部映射与文档）。
 * 新增后端命令时请同步更新此列表。
 */
export const SERVICE_COMMANDS: { command: string; hint: string }[] = [
  { command: 'connect', hint: '建立 MCP 连接，body 为 McpOptions' },
  { command: 'lookup-env-var', hint: 'body: { keys: string[] }' },
  { command: 'ping', hint: 'body: { clientId }' },
  { command: 'disconnect', hint: 'body: { clientId }' },
  { command: 'server/version', hint: 'body: { clientId }' },
  { command: 'prompts/list', hint: 'body: { clientId }' },
  { command: 'prompts/get', hint: 'body: { clientId, promptId, args? }' },
  { command: 'resources/list', hint: 'body: { clientId }' },
  { command: 'resources/templates/list', hint: 'body: { clientId }' },
  { command: 'resources/read', hint: 'body: { clientId, resourceUri }' },
  { command: 'tools/list', hint: 'body: { clientId }' },
  { command: 'tools/call', hint: 'body: { clientId, toolName, toolArgs, callToolOption? }' },
  { command: 'llm/chat/completions', hint: '流式聊天（Web UI）；CLI 请用 llm/chat/completions/sync' },
  { command: 'llm/chat/completions/abort', hint: 'body: { sessionId }' },
  { command: 'llm/models', hint: 'body: { baseURL, apiKey, proxyServer? }' },
  { command: 'llm/models/openrouter', hint: '无额外字段' },
  { command: 'llm/chat/completions/sync', hint: 'body: { baseURL, apiKey, model, messages, temperature? }' },
  { command: 'llm/models/dynamic', hint: 'body: { providerId }' },
  { command: 'panel/save', hint: 'body: { clientId, ... }' },
  { command: 'panel/load', hint: 'body: { clientId }' },
  { command: 'system-prompts/set', hint: 'body: { clientId, name, content }' },
  { command: 'system-prompts/delete', hint: 'body: { clientId, name }' },
  { command: 'system-prompts/save', hint: 'body: { clientId, prompts }' },
  { command: 'system-prompts/load', hint: 'body: { clientId }' },
  { command: 'variables/save', hint: 'body: { clientId, variables }' },
  { command: 'variables/load', hint: 'body: { clientId }' },
  { command: 'extraction-rules/save', hint: 'body: { clientId, extractionRules }' },
  { command: 'extraction-rules/load', hint: 'body: { clientId }' },
  { command: 'test-cases/save', hint: 'body: { clientId, testCases }' },
  { command: 'test-cases/load', hint: 'body: { clientId }' },
  { command: 'batch-validation/load', hint: 'body: { clientId }' },
  { command: 'batch-validation/save', hint: 'body: { clientId, storage }' },
  { command: 'batch-validation/run', hint: 'body: { messages, testCases, llmConfig, evaluationMode?, customPrompt? }' },
  { command: 'ocr/get-ocr-image', hint: 'body: { filename }' },
  { command: 'ocr/start-ocr', hint: 'body: { base64String, mimeType }' },
  { command: 'setting/save', hint: 'body: 任意设置对象' },
  { command: 'setting/load', hint: '加载设置' },
  { command: 'setting/set-tour', hint: 'body: { userHasReadGuide }' },
  { command: 'setting/get-tour', hint: '无额外字段' },
  { command: 'feedback/reflux', hint: 'body: { name, storage }' },
  { command: 'feedback/reflux/get-count', hint: 'body: { name }' },
  { command: 'feedback/reflux/get-data', hint: 'body: { name, page?, pageSize? }' },
  { command: 'feedback/reflux/findTraceByHash', hint: 'body: { name, hash }' },
  { command: 'feedback/reflux/findEnableToolsByHash', hint: 'body: { name, hash }' },
  { command: 'skills/list', hint: '列出技能' },
  { command: 'skills/load', hint: 'body: { skillName }' },
  { command: 'skills/read-file', hint: 'body: { skill_name, file_path }' },
  { command: 'debugger-mcp/load', hint: '加载调试器 MCP 配置' },
  { command: 'debugger-mcp/save', hint: 'body: { enabled?, port?, enabledTools? }' },
  { command: 'debugger-mcp/connection-info', hint: '连接信息' },
  { command: 'debugger-mcp/toggle-tool', hint: 'body: { toolName, enabled }' },
  { command: 'auth/login', hint: 'body: { username, password }' },
  { command: 'auth/register', hint: 'body: { email, username, password }' },
  { command: 'auth/oauth', hint: 'body: { channel, redirectUri? }' },
  { command: 'auth/oauth/finalize', hint: 'body: { nonce }' },
  { command: 'auth/device/start', hint: 'body: { channel }' },
  { command: 'auth/device/token', hint: 'body: { deviceCode }' },
  { command: 'auth/logout', hint: '' },
  { command: 'auth/logout-all', hint: '' },
  { command: 'auth/status', hint: '' },
  { command: 'auth/refresh', hint: '' },
  { command: 'auth/set-token', hint: 'body: { token }' },
  { command: 'auth/set-token-pair', hint: 'body: { accessToken, refreshToken, user? }' },
  { command: 'auth/get-token', hint: '' },
  { command: 'auth/clear-token', hint: '' },
  { command: 'projects/create', hint: 'body: { name }' },
  { command: 'projects/list', hint: '' },
  { command: 'projects/get', hint: 'body: { projectId }' },
  { command: 'projects/update', hint: 'body: { projectId, name }' },
  { command: 'projects/delete', hint: 'body: { projectId }' },
  { command: 'projects/members/list', hint: 'body: { projectId }' },
  { command: 'projects/members/add', hint: 'body: { projectId, userId, role }' },
  { command: 'projects/members/remove', hint: 'body: { projectId, userId }' },
  { command: 'projects/members/update-role', hint: 'body: { projectId, userId, role }' },
  { command: 'projects/invites/list', hint: 'body: { projectId }' },
  { command: 'projects/invites/create', hint: 'body: { projectId, role, expiresAt?, maxUses? }' },
  { command: 'projects/invites/delete', hint: 'body: { projectId, inviteId }' },
  { command: 'projects/invites/revoke', hint: 'body: { projectId, inviteId }' },
  { command: 'invites/join', hint: 'body: { code, userId }' },
  { command: 'spec-cases/create', hint: 'body: { projectId, nodeType, type, name, parentId?, input?, output? }' },
  { command: 'spec-cases/tree', hint: 'body: { projectId }' },
  { command: 'spec-cases/get', hint: 'body: { projectId, caseId }' },
  { command: 'spec-cases/update', hint: 'body: { projectId, caseId, nodeType, type, name, parentId?, input?, output? }' },
  { command: 'spec-cases/delete', hint: 'body: { projectId, caseId }' }
];
