name: Build & Test VSCode Extension

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build monorepo
      run: npm run build

    - name: Compile TypeScript
      run: npx tsc

    - name: Package VSIX
      run: npx vsce package --out dist/openmcp.vsix

    - name: Upload VSIX
      uses: actions/upload-artifact@v4
      with:
        name: openmcp-${{ matrix.os }}
        path: dist/openmcp.vsix

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '22.x'
  #       cache: 'npm'

  #   - name: Install test dependencies
  #     run: npm install && npm run test